default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV["DB_DATABASE"] %>
  host: <%= ENV["DB_HOST"] %>
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>

development:
  <<: *default
  
test:
  <<: *default
  database: taberoute_backend_test
production:
  <<: *default
  database: taberoute_backend_production
  username: taberoute_backend
  password: <%= ENV["TABEROUTE_BACKEND_DATABASE_PASSWORD"] %>
